/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.donutnv.doan.java.chess;

import javax.swing.JTextField;

/**
 *
 * @author Chi Nguyen
 */
public class formEmail extends javax.swing.JFrame {

    /**
     * Creates new form formForgotPass
     */
    public formEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        btnsendcode = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        btnconfirmcode = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtusername = new javax.swing.JTextField();
        txtconfirmcode = new javax.swing.JPasswordField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(51, 51, 51));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnsendcode.setBackground(new java.awt.Color(102, 102, 102));
        btnsendcode.setFont(new java.awt.Font("Tempus Sans ITC", 1, 10)); // NOI18N
        btnsendcode.setForeground(new java.awt.Color(255, 255, 255));
        btnsendcode.setText("SEND");
        btnsendcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsendcodeActionPerformed(evt);
            }
        });
        jPanel5.add(btnsendcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 340, 70, 20));

        jSeparator1.setBackground(new java.awt.Color(255, 255, 255));
        jSeparator1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 143, 280, 0));

        btnconfirmcode.setBackground(new java.awt.Color(102, 102, 102));
        btnconfirmcode.setFont(new java.awt.Font("Tempus Sans ITC", 1, 34)); // NOI18N
        btnconfirmcode.setForeground(new java.awt.Color(255, 255, 255));
        btnconfirmcode.setText("CONFIRM CODE");
        btnconfirmcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnconfirmcodeActionPerformed(evt);
            }
        });
        jPanel5.add(btnconfirmcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 310, 70));

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Chi Nguyen\\Downloads\\R.png")); // NOI18N
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 260, 220));

        jLabel4.setFont(new java.awt.Font("Pristina", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("FORGOT PASSWORD");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 260, -1, -1));

        txtusername.setBackground(new java.awt.Color(51, 51, 51));
        txtusername.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtusername.setForeground(new java.awt.Color(255, 255, 255));
        txtusername.setText("Your email ");
        txtusername.setBorder(null);
        txtusername.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtusernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtusernameFocusLost(evt);
            }
        });
        jPanel5.add(txtusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 330, 317, 32));

        txtconfirmcode.setBackground(new java.awt.Color(51, 51, 51));
        txtconfirmcode.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        txtconfirmcode.setForeground(new java.awt.Color(255, 255, 255));
        txtconfirmcode.setText("Confirm Code");
        txtconfirmcode.setBorder(null);
        txtconfirmcode.setEchoChar('\u0000');
        txtconfirmcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtconfirmcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtconfirmcodeFocusLost(evt);
            }
        });
        jPanel5.add(txtconfirmcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 390, -1, -1));
        jPanel5.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 360, 190, 30));
        jPanel5.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 190, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 584, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnconfirmcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnconfirmcodeActionPerformed

        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnconfirmcodeActionPerformed

    private void txtconfirmcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmcodeFocusLost
        // TODO add your handling code here:
        if(txtconfirmcode.getText().length()==0){
            addPlaceholderStyle(txtconfirmcode);
            txtconfirmcode.setText("Confirm Code");
            txtconfirmcode.setEchoChar('\u0000');
        }
    }//GEN-LAST:event_txtconfirmcodeFocusLost

    private void txtconfirmcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtconfirmcodeFocusGained
        // TODO add your handling code here:
        if(txtconfirmcode.getText().equals("Confirm Code")){
            txtconfirmcode.setText(null);
            txtconfirmcode.requestFocus();

            
            removePlaceholderStyle(txtconfirmcode);
        }
    }//GEN-LAST:event_txtconfirmcodeFocusGained

    private void txtusernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusLost
        // TODO add your handling code here:
        if(txtusername.getText().length()==0){
            addPlaceholderStyle(txtusername);
            txtusername.setText("Your email ");
        }
    }//GEN-LAST:event_txtusernameFocusLost

    private void txtusernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtusernameFocusGained
        // TODO add your handling code here:
        if(txtusername.getText().equals("Your email ")){
            txtusername.setText(null);
            txtusername.requestFocus();

            removePlaceholderStyle(txtusername);
        }
    }//GEN-LAST:event_txtusernameFocusGained

    private void btnsendcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsendcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnsendcodeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formEmail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formEmail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnconfirmcode;
    private javax.swing.JButton btnsendcode;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JPasswordField txtconfirmcode;
    private javax.swing.JTextField txtusername;
    // End of variables declaration//GEN-END:variables

    private void addPlaceholderStyle(JTextField txtusername) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    private void removePlaceholderStyle(JTextField txtusername) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
