/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.donutnv.doan.java.chess;



import com.donutnv.doan.java.chess.display.*;
import com.donutnv.doan.java.chess.pieces.AbstractPiece;
import com.donutnv.doan.java.chess.pieces.Bishop;
import com.donutnv.doan.java.chess.pieces.King;
import com.donutnv.doan.java.chess.pieces.Knight;
import com.donutnv.doan.java.chess.pieces.Pawn;
import com.donutnv.doan.java.chess.pieces.Queen;
import com.donutnv.doan.java.chess.pieces.Rook;
import java.awt.*;

import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;

/**
 *
 * @author nguye
 */
public class GameBoard extends javax.swing.JFrame {

    public static final Font TEXT_FONT = new Font("Arial", Font.PLAIN, 20);
    public static final Font BUTTON_FONT = new Font("Arial Unicode MS", Font.PLAIN, 65);
    public static final Color LIGHT_COLOR = new Color(239,255,191);
    public static final Color DARK_COLOR = new Color(0,153,51);
    public static final Color MOVE_COLOR = new Color(204,255,51);

    public static AbstractPiece movingPiece = null;
    public static int[] from = null;
    public static int[] to = null;
    
    public static ButtonPiece[][] btnsPiece;
    public static String Player;
    public static AbstractPiece[] pieces;
    public static JTextArea logText;
    public static JLabel turnLabel;

    /**
     * Creates new form Gameboard
     */
    public GameBoard() {
        initComponents();
        
        Player = "white";
        //tao ban co
        btnsPiece = new ButtonPiece[8][8];
        pieces = new AbstractPiece[32];
        setPieces(pieces);
        setBtns(btnsPiece, pieces, jPanelBoardGame);
    }


    static void setBtns(ButtonPiece[][] btns, AbstractPiece[] pieces, JPanel panel) {
        Color bg = LIGHT_COLOR;
        for (int i = 0, y = 0; i < 8; i++) {
            for (int j = 0; j < 8; j++) {
                if (i == 0 || i == 1 || i == 6 || i == 7) {
                    ButtonPiece btn = new ButtonPiece(pieces[y], new int[]{i, j}, bg);
                    btns[i][j] = btn;
                    y++;
                } else {
                    ButtonPiece btn = new ButtonPiece(new int[]{i, j}, bg);
                    btns[i][j] = btn;
                }
                panel.add(btns[i][j]);
                bg = bg == LIGHT_COLOR ? DARK_COLOR : LIGHT_COLOR;
            }
            bg = bg == LIGHT_COLOR ? DARK_COLOR : LIGHT_COLOR;
        }
    }

    static void setPieces(AbstractPiece[] pieces) {
        pieces[0] = new Rook(new int[]{0, 0}, "\u265C", "black");
        pieces[1] = new Knight(new int[]{0, 1}, "\u265E", "black");
        pieces[2] = new Bishop(new int[]{0, 2}, "\u265D", "black");
        pieces[3] = new Queen(new int[]{0, 3}, "\u265B", "black");
        pieces[4] = new King(new int[]{0, 4}, "\u265A", "black");
        pieces[5] = new Bishop(new int[]{0, 5}, "\u265D", "black");
        pieces[6] = new Knight(new int[]{0, 6}, "\u265E", "black");
        pieces[7] = new Rook(new int[]{0, 7}, "\u265C", "black");
        for (int i = 8, j = 0; i < 16; i++, j++) {
            pieces[i] = new Pawn(new int[]{1, j}, "\u265F", "black");
        }
        for (int i = 16, j = 0; i < 24; i++, j++) {
            pieces[i] = new Pawn(new int[]{6, j}, "\u2659", "white");
        }
        pieces[24] = new Rook(new int[]{7, 0}, "\u2656", "white");
        pieces[25] = new Knight(new int[]{7, 1}, "\u2658", "white");
        pieces[26] = new Bishop(new int[]{7, 2}, "\u2657", "white");
        pieces[27] = new Queen(new int[]{7, 3}, "\u2655", "white");
        pieces[28] = new King(new int[]{7, 4}, "\u2654", "white");
        pieces[29] = new Bishop(new int[]{7, 5}, "\u2657", "white");
        pieces[30] = new Knight(new int[]{7, 6}, "\u2658", "white");
        pieces[31] = new Rook(new int[]{7, 7}, "\u2656", "white");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelBoardGame = new javax.swing.JPanel();
        jPanelMenu = new javax.swing.JPanel();
        jScrollPaneLog = new javax.swing.JScrollPane();
        lblLog = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Chess");
        setSize(new java.awt.Dimension(500, 500));

        jPanelBoardGame.setLayout(new java.awt.GridLayout(8, 8));

        jScrollPaneLog.setBorder(null);
        jScrollPaneLog.setAlignmentX(0.0F);
        jScrollPaneLog.setAlignmentY(0.0F);

        lblLog.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblLog.setText("Log:");
        lblLog.setEnabled(false);

        javax.swing.GroupLayout jPanelMenuLayout = new javax.swing.GroupLayout(jPanelMenu);
        jPanelMenu.setLayout(jPanelMenuLayout);
        jPanelMenuLayout.setHorizontalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPaneLog, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(lblLog, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelMenuLayout.setVerticalGroup(
            jPanelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMenuLayout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jScrollPaneLog, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblLog, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(94, 94, 94))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBoardGame, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBoardGame, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
            .addComponent(jPanelMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameBoard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameBoard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanelBoardGame;
    private javax.swing.JPanel jPanelMenu;
    private javax.swing.JScrollPane jScrollPaneLog;
    private javax.swing.JLabel lblLog;
    // End of variables declaration//GEN-END:variables
}
